import Head from 'next/head'
import Link from 'next/link'
import {Poppins} from 'next/font/google'

const poppins = Poppins({
  weight: ['400','700'],
  subsets:['latin']
})

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <ul className={poppins.className}>
      <li>
        <Link href="/">Home</Link>
      </li>
      <li>
        <Link href="/about">About Us</Link>
      </li>
      <li>
        <Link href="/blog">Blog Post</Link>
      </li>
    </ul>
    </div>
  )
}
